AWSTemplateFormatVersion: "2010-09-09"
# Version 1.0 - Initial version
Description: Template to create IAM users. Version 1.0

Parameters:
  UserName:
    Type: String
  Password:
    Type: String
    NoEcho: True
  ManagedPolicyArns:
    Description: Comma-separated list of IAM Policy ARNs
    Type: String
    Default: ""
  Serial:
    Description: Increment this number by one to rotate the user's IAM Access Key
    Type: String
    Default: 1

Conditions:
  HasAdditionalPolicies: !Not [ !Equals [ !Ref ManagedPolicyArns, "" ] ]

Resources:
  IAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Join ["-", [ iam-user, !Ref UserName ] ]
      LoginProfile:
        Password: !Ref Password
      ManagedPolicyArns:
        !If
          - HasAdditionalPolicies
          - !Split
            - ','
            - !Join
              - ','
              - - !ImportValue iam-policy-enforce-mfa
                - !Ref ManagedPolicyArns
          - - !ImportValue iam-policy-enforce-mfa

  IAMAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Serial: !Ref Serial
      UserName: !Ref IAMUser

  IAMSecretKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref IAMUser
      Description: IAM User Secret Key
      SecretString: !Sub '{"accesskey": "${IAMAccessKey}", "secretkey": "${IAMAccessKey.SecretAccessKey}"}'

Outputs:
  IAMUser:
    Value: !Ref IAMUser
