AWSTemplateFormatVersion: "2010-09-09"

# TODO: EC2 - Create CW disk usage alarms/monitoring
#       RDS - Create CW disk usage alarms/monitoring

# TODO: Ability to restore

Description: JIRA

Parameters:
  # ===== General Section =====
  S3Templates:
    Type: AWS::SSM::Parameter::Value<String>
    Default: S3Templates
  VPCName:
    Type: String
    Default: ised
  JIRAProjectKey:
    Type: String
    Default: jira
  CostCentre:
    Type: String
    Default: cio-rdad
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  Subnet:
    Type: String
    Default: subneta
    AllowedValues:
      - subneta
      - subnetb
  EC2Ami:
    Type: String
    Description: Specify if restoring from Ami, otherwise leave blank

  # ===== EBS Volumes =====
  EC2RootVolumeSize:
    Type: String
    Default: 8
  EC2AppVolumeSize:
    Type: String
    Default: 2
  EC2AppVolumeMount:
    Type: String
    Default: /dev/sdg
  EC2DataVolumeSize:
    Type: String
    Default: 20
  EC2DataVolumeMount:
    Type: String
    Default: /dev/sdf

  # ===== RDS Section =====
  RDSStorage:
    Type: String
    Default: 20
  RDSSize:
    Type: String
    Default: db.t3.large
  RDSEngine:
    Type: String
    Default: postgres
  RDSEngineVersion:
    Type: String
    Default: 9.6.15
  RDSSnapshot:
    Description: Specify if restoring from snapshot
    Type: String
  RDSMasterUserPassword:
    NoEcho: true
    Type: String

Conditions:
  IsProd: !Equals [ !Ref Environment, prod ]
  IsEC2Restore: !Equals [ !Ref EC2Ami, "" ]
  IsRDSRestore: !Equals [ !Ref RDSSnapshot, "" ]

Resources:

  EC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      ## TemplateURL: !Join [ '', [!Ref S3Templates, "ec2.yaml" ]]
      TemplateURL: "https://ised-sb-test.s3.ca-central-1.amazonaws.com/ec2.yaml"
      Parameters:
        # ===== General Section =====
        JIRAProjectKey: !Ref JIRAProjectKey
        CostCentre: !Ref CostCentre
        Environment: !Ref Environment
        VPCName: !Ref VPCName
        Subnet: !Ref Subnet
        Schedule: !If [ IsProd, 24-7, office-hours ]

        # ===== EC2 Section =====
        CreateEC2: !If [ IsEC2Restore, Linux-Restore, Linux ]
        EC2Size: t3.large
        EC2Ami: !Ref EC2Ami
        EC2RootVolumeSize: !Ref EC2RootVolumeSize

        # ===== EBS Section =====
        EBSMount: no # TODO
        EBSSize: "AWS::NoValue" # TODO

  EBSAppVolume:
    Type: AWS::EC2::Volume
    Properties:
      Size: !Ref EC2AppVolumeSize
      AvailabilityZone:
        Fn::ImportValue:
          !Sub "${JIRAProjectKey}-${Environment}-ec2-az"
      Encrypted: true
      Tags:
      - Key: Name
        Value: !Join ['-', ["ebs", !Ref "AWS::AccountId", !Ref "JIRAProjectKey", !Ref "Environment" ] ]
      - Key: ised-cost-centre
        Value: !Ref CostCentre
      - Key: ised-project-id
        Value: ccots-jira
      - Key: ised-environment
        Value: !Ref Environment
      - Key: ised-backup
        Value: !If [ IsProd, backup-prod, backup-dev ]
    DeletionPolicy: Snapshot

  EBSAppMountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId:
        Fn::ImportValue:
          !Sub "${JIRAProjectKey}-${Environment}-ec2"
      VolumeId: !Ref EBSAppVolume
      Device: !Ref EC2AppVolumeMount

  EBSDataVolume:
    Type: AWS::EC2::Volume
    Properties:
      Size: !Ref EC2DataVolumeSize
      AvailabilityZone:
        Fn::ImportValue:
          !Sub "${JIRAProjectKey}-${Environment}-ec2-az"
      Encrypted: true
      Tags:
      - Key: Name
        Value: !Join ['-', ["ebs", !Ref "AWS::AccountId", !Ref "JIRAProjectKey", !Ref "Environment" ] ]
      - Key: ised-cost-centre
        Value: !Ref CostCentre
      - Key: ised-project-id
        Value: ccots-jira
      - Key: ised-environment
        Value: !Ref Environment
      - Key: ised-backup
        Value: !If [ IsProd, backup-prod, backup-dev ]
    DeletionPolicy: Snapshot

  EBSDataMountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId:
        Fn::ImportValue:
          !Sub "${JIRAProjectKey}-${Environment}-ec2"
      VolumeId: !Ref EBSDataVolume
      Device: !Ref EC2DataVolumeMount

  RDS:
    Type: AWS::CloudFormation::Stack
    Properties:
      ## TemplateURL: !Join [ '', [!Ref S3Templates, "rds.yaml" ]]
      TemplateURL: "https://ised-sb-test.s3.ca-central-1.amazonaws.com/rds.yaml"
      Parameters:
        # ===== General Section =====
        JIRAProjectKey: !Ref JIRAProjectKey
        CostCentre: !Ref CostCentre
        Environment: !Ref Environment
        VPCName: !Ref VPCName
        Schedule: !If [ IsProd, 24-7, office-hours ]
        # ===== RDS Section =====
        RDSEngine: !Ref RDSEngine
        RDSEngineVersion: !Ref RDSEngineVersion
        RDSStorage: !Ref RDSStorage
        RDSSize: !Ref RDSSize
        RDSSnapshot: !Ref RDSSnapshot
        RDSBackupRetentionPeriod: !If [ IsProd, 30, 7 ]
        RDSMasterUserPassword: !Ref RDSMasterUserPassword
