#!/bin/bash
# ./update-stack secrets

if [[ $# -eq 0 ]] ; then
    echo "Usage: update-stack <stackname>"
    echo ""
    echo "Example: update-stack secrets"
    exit 1
fi

# Default variable values
stack=$1
extra_params=""
accounts_param="--accounts file://./../scripts/accounts.json"

if [ "${stack}" == "roles" ]
then
    extra_params="--capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM"
elif [ "${stack}" == "???" ]
then
    accounts_param="--accounts ou-d4vw-fxuqomrt"
fi

aws cloudformation update-stack-set --stack-set-name ised-"${stack}" --template-url https://ised-s3-256255698049-cf.s3.ca-central-1.amazonaws.com/cf-stacks/"${stack}".yaml --parameters file://./../cf-parameters/"${stack}".json "${accounts_param}" --regions ca-central-1 "${extra_params}"

#aws cloudformation update-stack-set --stack-set-name ised-$1 --template-url https://ised-s3-256255698049-cf.s3.ca-central-1.amazonaws.com/cf-stacks/$1.yaml --parameters file://./../cf-parameters/$1.json --accounts ou-d4vw-fxuqomrt --regions ca-central-1

