AWSTemplateFormatVersion: "2010-09-09"

Description: Confluence

Parameters:
  # ===== General Section =====
  S3Templates:
    Type: AWS::SSM::Parameter::Value<String>
    Default: S3Templates
  VPCName:
    Type: String
    Default: ised
  JIRAProjectKey:
    Type: String
    Default: confluence
  ISEDProjectId:
    Type: String
    Default: ccots-confluence
  CostCentre:
    Type: String
    Default: cio-rdad
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  Subnet:
    Type: String
    Default: subneta
    AllowedValues:
      - subneta
      - subnetb
  EC2Ami:
    Type: String
    Description: Specify if restoring from Ami, otherwise leave blank

  # ===== EBS Volumes =====
  EC2RootVolumeSize:
    Type: String
    Default: 8
  EC2AppVolumeSize:
    Type: String
    Default: 2
  EC2AppVolumeMount:
    Type: String
    Default: /dev/sdg
  EC2DataVolumeSize:
    Type: String
    Default: 20
  EC2DataVolumeMount:
    Type: String
    Default: /dev/sdf

  # ===== RDS Section =====
  RDSStorage:
    Type: String
    Default: 20
  RDSSize:
    Type: String
    Default: db.t3.medium
  RDSEngine:
    Type: String
    Default: postgres
  RDSEngineVersion:
    Type: String
    Default: 9.6.15
  DBIdentifier:
    Type: String
    Default: confluence
  RDSSnapshot:
    Description: Specify if restoring from snapshot
    Type: String
  RDSMasterUserPassword:
    NoEcho: true
    Type: String

Conditions:
  IsProd: !Equals [ !Ref Environment, prod ]
  IsEC2Restore: !Equals [ !Ref EC2Ami, "" ]
  IsRDSRestore: !Equals [ !Ref RDSSnapshot, "" ]

Resources:

  EC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join [ '', [!Ref S3Templates, "ec2.yaml" ]]
      Parameters:
        # ===== General Section =====
        JIRAProjectKey: !Ref JIRAProjectKey
        ISEDProjectId: !Ref ISEDProjectId
        CostCentre: !Ref CostCentre
        Environment: !Ref Environment
        VPCName: !Ref VPCName
        Subnet: !Ref Subnet
        Schedule: !If [ IsProd, 24-7, office-hours ]

        # ===== EC2 Section =====
        CreateEC2: Linux
        EC2Size: t3.large
        EC2Ami: !Ref EC2Ami
        EC2RootVolumeSize: !Ref EC2RootVolumeSize
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -xe

            # Create directories
            mkdir -p /opt/atlassian/confluence /var/atlassian/application-data/confluence

            # Wait until the volume shows up
            while [ ! -e ${EBSDataVolume} ]; do echo Waiting for EBS Data volume to attach; sleep 5; done

            # Create filesystem
            mkfs -t xfs "${EBSDataMount}"

            # Add an entry to fstab to mount volume during boot
            echo "${EBSDataVolume}    /var/atlassian/application-data/confluence xfs    defaults,noatime,nofail    0    2" >> /etc/fstab

            # Wait until the volume shows up
            while [ ! -e ${EBSAppMount} ]; do echo Waiting for EBS App volume to attach; sleep 5; done

            # Create filesystem
            mkfs -t xfs "${EBSAppVolume}"

            # Add an entry to fstab to mount volume during boot
            echo "${EBSAppVolume}     /opt/atlassian/confluence                xfs    defaults,noatime,nofail    0    2" >> /etc/fstab

            # Mount the volumes on current boot
            mount -a

            # Install deps
            yum install -y fontconfig patch java-1.8.0-openjdk

            # Get custom files
            wget https://github.com/stephane-berube/cots-mods/archive/confluence.zip -O /tmp/pkg.zip
            unzip /tmp/pkg.zip -d /tmp

            # Get and run Confluence installer
            wget "${ConfluenceInstallerUrl}" -O /tmp/installer.bin
            chmod u+x /tmp/installer.bin
            yes '' | /tmp/installer.bin

            # Stop the running Confluence instance
            service confluence stop

            # Setup logging to be logrotate-friendly
            cat /tmp/cots-mods-confluence/logging.properties.suffix >> /opt/atlassian/confluence/conf/logging.properties
            mv /tmp/cots-mods-confluence/confluence.logrotate /etc/logrotate.d/confluence.conf

            # Disable the old Confluence boot-time startup
            systemctl disable confluence

            # Copy our systemd unit file
            mv /tmp/cots-mods-confluence/confluence.service /etc/systemd/system/confluence.service

            # Refresh systemd daemons since we've added a new unit file
            # start Confluence and enable startup at boot-time
            systemctl daemon-reload
            systemctl enable confluence --now

            # Cleanup
            rm -r /tmp/cots-mods-confluence /tmp/pkg.zip /tmp/installer.bin

  EBSAppVolume:
    Type: AWS::EC2::Volume
    Properties:
      Size: !Ref EC2AppVolumeSize
      AvailabilityZone: !GetAtt EC2.Outputs.AvailabilityZone
      Encrypted: true
      Tags:
      - Key: Name
        Value: !Join ['-', ["ebs", !Ref "AWS::AccountId", !Ref "JIRAProjectKey", !Ref "Environment" ] ]
      - Key: ised-cost-centre
        Value: !Ref CostCentre
      - Key: ised-project-id
        Value: ccots-confluence
      - Key: ised-environment
        Value: !Ref Environment
      - Key: ised-backup
        Value: !If [ IsProd, backup-prod, backup-dev ]
    DeletionPolicy: Snapshot

  EBSAppMountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !GetAtt EC2.Outputs.InstanceId
      VolumeId: !Ref EBSAppVolume
      Device: !Ref EC2AppVolumeMount

  EBSDataVolume:
    Type: AWS::EC2::Volume
    Properties:
      Size: !Ref EC2DataVolumeSize
      AvailabilityZone: !GetAtt EC2.Outputs.AvailabilityZone
      Encrypted: true
      Tags:
      - Key: Name
        Value: !Join ['-', ["ebs", !Ref "AWS::AccountId", !Ref "JIRAProjectKey", !Ref "Environment" ] ]
      - Key: ised-cost-centre
        Value: !Ref CostCentre
      - Key: ised-project-id
        Value: ccots-confluence
      - Key: ised-environment
        Value: !Ref Environment
      - Key: ised-backup
        Value: !If [ IsProd, backup-prod, backup-dev ]
    DeletionPolicy: Snapshot

  EBSDataMountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !GetAtt EC2.Outputs.InstanceId
      VolumeId: !Ref EBSDataVolume
      Device: !Ref EC2DataVolumeMount

  # Allow incoming connection on Confluence's listening port from ALB VPC
  IngressConfluence:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !GetAtt EC2.Outputs.EC2SecurityGroup
      IpProtocol: tcp
      FromPort: 8090
      ToPort: 8090
      CidrIp: 100.96.192.0/24

  # Allow incoming connection on Crowd's listening port from Confluence's sg
  IngressCrowd:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Fn::ImportValue:
          Fn::Sub:  "sg-ec2-crowd-${Environment}"
      IpProtocol: tcp
      FromPort: 8095
      ToPort: 8095
      SourceSecurityGroupId: !GetAtt EC2.Outputs.EC2SecurityGroup

  RDS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join [ '', [!Ref S3Templates, "rds.yaml" ]]
      Parameters:
        # ===== General Section =====
        DBIdentifier: !Ref DBIdentifier
        ISEDProjectId: !Ref ISEDProjectId
        CostCentre: !Ref CostCentre
        Environment: !Ref Environment
        VPCName: !Ref VPCName
        VPCId:
          Fn::ImportValue:
            Fn::Sub: "vpc-${VPCName}-${Environment}"
        Schedule: !If [ IsProd, 24-7, office-hours ]
        # ===== RDS Section =====
        RDSEngine: !Ref RDSEngine
        RDSEngineVersion: !Ref RDSEngineVersion
        RDSStorage: !Ref RDSStorage
        RDSSize: !Ref RDSSize
        RDSSnapshot: !Ref RDSSnapshot
        RDSBackupRetentionPeriod: !If [ IsProd, 30, 7 ]
        RDSMasterUserPassword: !Ref RDSMasterUserPassword

  IngressPostgres:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allow incoming connections from EC2s from VPC to RDS on port 5432 (Postgresql)
      GroupId: !GetAtt RDS.Outputs.RDSSecurityGroup
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      CidrIp:
        Fn::ImportValue:
          Fn::Sub:  "vpc-cidrblock-${VPCName}-${Environment}"
