AWSTemplateFormatVersion: "2010-09-09"

Description: Crowd

Parameters:
  # ===== General Section =====
  S3Templates:
    Type: AWS::SSM::Parameter::Value<String>
    Default: S3Templates
  VPCName:
    Type: String
    Default: ised
  JIRAProjectKey:
    Type: String
    Default: crowd
  ISEDProjectId:
    Type: String
    Default: ccots-crowd
  CostCentre:
    Type: String
    Default: cio-rdad
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  Subnet:
    Type: String
    Default: subneta
    AllowedValues:
      - subneta
      - subnetb
  EC2Ami:
    Type: String
    Description: Specify if restoring from Ami, otherwise leave blank

  # ===== EBS Volumes =====
  EC2RootVolumeSize:
    Type: String
    Default: 8
  EC2AppVolumeSize:
    Type: String
    Default: 2
  EC2AppVolumeMount:
    Type: String
    Default: /dev/sdg
  EC2DataVolumeSize:
    Type: String
    Default: 20
  EC2DataVolumeMount:
    Type: String
    Default: /dev/sdf

  # ===== RDS Section =====
  RDSStorage:
    Type: String
    Default: 20
  RDSSize:
    Type: String
    Default: db.t3.large
  RDSEngine:
    Type: String
    Default: postgres
  RDSEngineVersion:
    Type: String
    Default: 9.6.15
  DBIdentifier:
    Type: String
    Default: crowd
  RDSSnapshot:
    Description: Specify if restoring from snapshot
    Type: String
  RDSMasterUserPassword:
    NoEcho: true
    Type: String

Conditions:
  IsProd: !Equals [ !Ref Environment, prod ]
  IsEC2Restore: !Equals [ !Ref EC2Ami, "" ]
  IsRDSRestore: !Equals [ !Ref RDSSnapshot, "" ]

Resources:

  EC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join [ '', [!Ref S3Templates, "ec2.yaml" ]]
      Parameters:
        # ===== General Section =====
        JIRAProjectKey: !Ref JIRAProjectKey
        ISEDProjectId: !Ref ISEDProjectId
        CostCentre: !Ref CostCentre
        Environment: !Ref Environment
        VPCName: !Ref VPCName
        Subnet: !Ref Subnet
        Schedule: !If [ IsProd, 24-7, office-hours ]

        # ===== EC2 Section =====
        CreateEC2: Linux
        EC2Size: t3.large
        EC2Ami: !Ref EC2Ami
        EC2RootVolumeSize: !Ref EC2RootVolumeSize
        # SecurityGroupIds: !Ref SecurityGroupAtlassianEC2
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -xe

            # Create directories
            mkdir -p /opt/atlassian/ /var/atlassian/application-data/crowd

            # Wait until the volume shows up
            while [ ! -e ${EBSDataVolume} ]; do echo Waiting for EBS Data volume to attach; sleep 5; done

            # Create filesystem
            mkfs -t xfs "${EBSDataVolume}"

            # Add an entry to fstab to mount volume during boot
            echo "${EBSDataVolume}    /var/atlassian/application-data/crowd xfs    defaults,noatime,nofail    0    2" >> /etc/fstab

            # Wait until the volume shows up
            while [ ! -e ${EBSAppVolume} ]; do echo Waiting for EBS App volume to attach; sleep 5; done

            # Create filesystem
            mkfs -t xfs "${EBSAppVolume}"

            # Add an entry to fstab to mount volume during boot
            echo "${EBSAppVolume}     /opt/atlassian/crowd                xfs    defaults,noatime,nofail    0    2" >> /etc/fstab

            # Mount the volumes on current boot
            mount -a

            # Install deps
            yum install -y fontconfig

            # Get custom files
            wget https://github.com/stephane-berube/cots-mods/archive/crowd.zip -O /tmp/pkg.zip
            unzip /tmp/pkg.zip -d /tmp

            # Get and extract Crowd archive
            wget "${CrowdArchiveUrl}" -O /tmp/atlassian-crowd.tar.gz
            tar -C /opt/atlassian -xf /tmp/atlassian-crowd.tar.gz
            rename atlassian-crowd* crowd /opt/atlassian/*

            # Create user, set permissions
            adduser crowd
            chown -R crowd:crowd /opt/atlassian /var/atlassian/application-data

            # Set crowd home directory
            echo 'crowd.home=/var/atlassian/application-data/crowd' >> /opt/atlassian/crowd/crowd-webapp/WEB-INF/classes/crowd-init.properties

            # Setup logging to be logrotate-friendly
            cat /tmp/cots-mods-crowd/logging.properties.suffix >> /opt/atlassian/crowd/apache-tomcat/conf/logging.properties
            mv /tmp/cots-mods-crowd/crowd.logrotate /etc/logrotate.d/crowd.conf

            # Copy our systemd unit file
            mv /tmp/cots-mods-crowd/crowd.service /etc/systemd/system/crowd.service

            # Refresh systemd daemons since we've added a new unit file
            # start Crowd and enable startup at boot-time
            systemctl daemon-reload
            systemctl enable crowd --now

            # Cleanup
            rm -r /tmp/cots-mods-crowd /tmp/pkg.zip /tmp/atlassian-crowd.tar.gz

  EBSAppVolume:
    Type: AWS::EC2::Volume
    Properties:
      Size: !Ref EC2AppVolumeSize
      AvailabilityZone: !GetAtt EC2.Outputs.AvailabilityZone
      Encrypted: true
      Tags:
      - Key: Name
        Value: !Join ['-', ["ebs", !Ref "AWS::AccountId", !Ref "JIRAProjectKey", !Ref "Environment" ] ]
      - Key: ised-cost-centre
        Value: !Ref CostCentre
      - Key: ised-project-id
        Value: ccots-crowd
      - Key: ised-environment
        Value: !Ref Environment
      - Key: ised-backup
        Value: !If [ IsProd, backup-prod, backup-dev ]
    DeletionPolicy: Snapshot

  EBSAppMountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !GetAtt EC2.Outputs.InstanceId
      VolumeId: !Ref EBSAppVolume
      Device: !Ref EC2AppVolumeMount

  EBSDataVolume:
    Type: AWS::EC2::Volume
    Properties:
      Size: !Ref EC2DataVolumeSize
      AvailabilityZone: !GetAtt EC2.Outputs.AvailabilityZone
      Encrypted: true
      Tags:
      - Key: Name
        Value: !Join ['-', ["ebs", !Ref "AWS::AccountId", !Ref "JIRAProjectKey", !Ref "Environment" ] ]
      - Key: ised-cost-centre
        Value: !Ref CostCentre
      - Key: ised-project-id
        Value: ccots-crowd
      - Key: ised-environment
        Value: !Ref Environment
      - Key: ised-backup
        Value: !If [ IsProd, backup-prod, backup-dev ]
    DeletionPolicy: Snapshot

  EBSDataMountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !GetAtt EC2.Outputs.InstanceId
      VolumeId: !Ref EBSDataVolume
      Device: !Ref EC2DataVolumeMount

  # Allow incoming connection on Crowd's listening port from ALB VPC
  IngressCrowd:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !GetAtt EC2.Outputs.EC2SecurityGroup
      IpProtocol: tcp
      FromPort: 8095
      ToPort: 8095
      CidrIp: 100.96.192.0/24

  RDS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join [ '', [!Ref S3Templates, "rds.yaml" ]]
      Parameters:
        # ===== General Section =====
        DBIdentifier: !Ref DBIdentifier
        ISEDProjectId: !Ref ISEDProjectId
        CostCentre: !Ref CostCentre
        Environment: !Ref Environment
        VPCName: !Ref VPCName
        VPCId:
          Fn::ImportValue:
            Fn::Sub: "vpc-${VPCName}-${Environment}"
        Schedule: !If [ IsProd, 24-7, office-hours ]
        # ===== RDS Section =====
        RDSEngine: !Ref RDSEngine
        RDSEngineVersion: !Ref RDSEngineVersion
        RDSStorage: !Ref RDSStorage
        RDSSize: !Ref RDSSize
        RDSSnapshot: !Ref RDSSnapshot
        RDSBackupRetentionPeriod: !If [ IsProd, 30, 7 ]
        RDSMasterUserPassword: !Ref RDSMasterUserPassword

  # Allow incoming connections on port 5432 from this VPC
  IngressPostgres:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allow incoming connections from EC2s from VPC to RDS on port 5432 (Postgresql)
      GroupId: !GetAtt RDS.Outputs.RDSSecurityGroup
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      CidrIp:
        Fn::ImportValue:
          Fn::Sub:  "vpc-cidrblock-${VPCName}-${Environment}"

  # Atlassian related configuration
  SecurityGroupAtlassianEC2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Atlassian EC2 Security Group"
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "vpc-${VPCName}-${Environment}"
      Tags:
      - Key: Name
        Value: !Join ['-', ["sg-ec2-atlassian", !Ref Environment ] ]
      - Key: ised-cost-centre
        Value: cop-rdad
      - Key: ised-project-id
        Value: cops-aws
      - Key: ised-environment
        Value: !Ref Environment

  IngressAtlassian:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allow incoming connections between Atlassian COTS
      GroupId: !Ref SecurityGroupAtlassianEC2
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId: !Ref SecurityGroupAtlassianEC2

Outputs:
  SecurityGroupAtlassianEC2:
    Description: Security Group for all Atlassian EC2s
    Value: !GetAtt EC2.Outputs.EC2SecurityGroup
    Export:
      Name: !Join ['-', ["sg-ec2-crowd", !Ref "Environment" ]]
